Who adds all these bugs in my code?

diff --git a/pkgadd b/pkgadd
--- a/pkgadd
+++ b/pkgadd
@@ -38,12 +38,12 @@ stripcom()
     local _file="$1"
     local _line
     if [ -r "$_file" ]; then
-	{
-	    while read _line ; do
-		_line=${_line%%#*}
-		[ -n "$_line" ] && echo $_line
-	    done
-	} < $_file
+        {
+            while read _line ; do
+                _line=${_line%%#*}
+                [ -n "$_line" ] && echo $_line
+            done
+        } < $_file
     fi
 }
 
@@ -59,13 +59,13 @@ mktempfiles()
     dirsnewpackage=$DIR/dirsnewpackage
 
     # Put files and dirs in sepperate files.
-    $tar tvzf $path_package | egrep -v "(	var/package|	var$)" > $TMP1
+    $tar tvzf $path_package | egrep -v "(       var/package|    var$)" > $TMP1
     awk '/^[^d]/ {print $9}' $TMP1 > $filesnewpackage
     awk '/^d/    {print $9}' $TMP1 > $dirsnewpackage
 
     if [ -e $dbase/$name-footprint ]; then
-	awk -F '\t' '/^[^d]/ {print $3}' $dbase/$name-footprint > $filesoldpackage
-	awk -F '\t' '/^d/    {print $3}' $dbase/$name-footprint > $dirsoldpackage
+        awk -F '\t' '/^[^d]/ {print $3}' $dbase/$name-footprint > $filesoldpackage
+        awk -F '\t' '/^d/    {print $3}' $dbase/$name-footprint > $dirsoldpackage
     fi
 
     # remove them in any way the program exits.
@@ -96,34 +96,34 @@ isinstalled()
 find_conflicts()
 {
     (
-	# Put the footprint of this package ...
-	cat $filesnewpackage
-	# ... and all the footprints of all _other_ packages in
-	# the dbase on stdout.  /dev/null on the end is an empty
-	# file incase there are no packages installed.
-	awk -F '\t' '/^[^d]/ {print $3}' $(find $dbase -name '*-footprint' ! -name "$name-footprint") /dev/null
+        # Put the footprint of this package ...
+        cat $filesnewpackage
+        # ... and all the footprints of all _other_ packages in
+        # the dbase on stdout.  /dev/null on the end is an empty
+        # file incase there are no packages installed.
+        awk -F '\t' '/^[^d]/ {print $3}' $(find $dbase -name '*-footprint' ! -name "$name-footprint") /dev/null
     ) | sort | uniq -d > $TMP1
 
     # remove empty lines from $TMP1
     sed -i '/^$/d'  $TMP1
 
     if [ -s $TMP1 ]; then
-	cat $TMP1 | while read line; do
-	    if [ -z "$FORCE" ]; then
-		pkginfo -o $line || error 'aborting.'
-	    else
-		# Remove the conflicting line from the database.
-		# Make sure that's a "TAB$line$"
-		footprint=$(grep -l "	$line$" $dbase/*-footprint)
-		grep -v "	$line$" $footprint > $footprint.tmp
-		mv $footprint.tmp $footprint
-	    fi
-	done
-	if [ -z "$FORCE" ]; then
-	    error 12 "These files are conflicting. Use $n -f to force install"
-	else
-	    message "Unregistered conflicting files."
-	fi
+        cat $TMP1 | while read line; do
+            if [ -z "$FORCE" ]; then
+                pkginfo -o $line || error 'aborting.'
+            else
+                # Remove the conflicting line from the database.
+                # Make sure that's a "TAB$line$"
+                footprint=$(grep -l "   $line$" $dbase/*-footprint)
+                grep -v "       $line$" $footprint > $footprint.tmp
+                mv $footprint.tmp $footprint
+            fi
+        done
+        if [ -z "$FORCE" ]; then
+            error 12 "These files are conflicting. Use $n -f to force install"
+        else
+            message "Unregistered conflicting files."
+        fi
     fi
 }
 
@@ -136,21 +136,21 @@ version()
 verifypackage()
 {
     if [ ! -f "$1" ]; then
-	error 1 "\`$1' does not exist or is not a regular file."
+        error 1 "\`$1' does not exist or is not a regular file."
     fi
     if ! file -b $1| grep -q 'gzip compressed data'; then
-	error 1 "\`$1' is not a .tar.gz file."
+        error 1 "\`$1' is not a .tar.gz file."
     fi
     # strip path
     path_package=$1
     package=${1##*/}
     if [ $package = $path_package ]; then
-	path_package=$PWD/$package
+        path_package=$PWD/$package
     fi
     # strip everything from #
-    version_release_extension=${package##*\#}
+    version_release_extension=${package##*\_}
     version_release=${version_release_extension%.pkg.tar.gz}
-    name=${package%\#*}
+    name=${package%\_*}
     version=${version_release_extension%-*}
     release=${version_release##*-}
     [ -z "$name"    ] && error 1 "no packagename defined in \`$package'"
@@ -166,42 +166,42 @@ makepattern()
 {
     unset pattern
     if [ -r $root/$pkgadd_conf ]; then
-	pkgadd_conf=$root/$pkgadd_conf
+        pkgadd_conf=$root/$pkgadd_conf
     else
-	echo -n "Warning: no $root/$pkgadd_conf found. " >&2
-	if [ -r $pkgadd_conf ]; then
-	    pkgadd_conf=$pkgadd_conf
-	    echo "Using $pkgadd_conf." >&2
-	else
-	    echo
-	    return 1
-	fi
+        echo -n "Warning: no $root/$pkgadd_conf found. " >&2
+        if [ -r $pkgadd_conf ]; then
+            pkgadd_conf=$pkgadd_conf
+            echo "Using $pkgadd_conf." >&2
+        else
+            echo
+            return 1
+        fi
     fi
 
     set -- $(stripcom $pkgadd_conf)
     while [ $# -gt 0 ]; do
-	# Add other keywords, like `DENY'? TODO
-	case $1 in
-	    UPGRADE)
-		;;
-	    *)
-		error 1 "Illegal pattern in $pkgadd_conf"
-		;;
-	esac
+        # Add other keywords, like `DENY'? TODO
+        case $1 in
+            UPGRADE)
+                ;;
+            *)
+                error 1 "Illegal pattern in $pkgadd_conf"
+                ;;
+        esac
 
-	# YES patterns MUST precede NO patterns.
-	case $3 in
-	    YES)
-		pattern=" -s |$2|&| $pattern"
-		;;
-	    NO)
-		pattern="$pattern -s |$2|$rejects/$name/&|"
-		;;
-	    *)
-		error 1 "Illegal pattern in $pkgadd_conf"
-		;;
-	esac
-	shift 3
+        # YES patterns MUST precede NO patterns.
+        case $3 in
+            YES)
+                pattern=" -s |$2|&| $pattern"
+                ;;
+            NO)
+                pattern="$pattern -s |$2|$rejects/$name/&|"
+                ;;
+            *)
+                error 1 "Illegal pattern in $pkgadd_conf"
+                ;;
+        esac
+        shift 3
     done
 }
 
@@ -212,11 +212,11 @@ removeoldfiles()
     # but not in the new one.
     cat $filesnewpackage $filesoldpackage | sort | uniq -u | sed -e 's|\(.*\)|^\1$|' > $TMP1
     if [ -s $TMP1 ]; then
-	grep -f $TMP1 $filesoldpackage | xargs -r -I % rm -f "${root:=/}%"
+        grep -f $TMP1 $filesoldpackage | xargs -r -I % rm -f "${root:=/}%"
     fi
     cat $dirsnewpackage $dirsoldpackage | sort | uniq -u | sed -e 's|\(.*\)|^\1$|' > $TMP1
     if [ -s $TMP1 ]; then
-	grep -f $TMP1 $dirsoldpackage | xargs -r -I % rmdir -p "${root:=/}%" > /dev/null 2>&1
+        grep -f $TMP1 $dirsoldpackage | xargs -r -I % rmdir -p "${root:=/}%" > /dev/null 2>&1
     fi
 }
 
@@ -224,43 +224,43 @@ removeoldfiles()
 tarcommand()
 {
     if [ $(id -u) -eq 0 ]; then
-	# Remove old rejects from previous installs.
-	rm -rf $rejects/$name
-	$tar $pattern -zxpf $1 -C ${root:=/}
+        # Remove old rejects from previous installs.
+        rm -rf $rejects/$name
+        $tar $pattern -zxpf $1 -C ${root:=/}
     else
-	error 1 "Only root can add packages."
+        error 1 "Only root can add packages."
     fi
 }
 
 installrejects()
 {
     (
-	unset unrejected
-	cd $rejects/$name 2> /dev/null || return 1
-	for i in $(find . ! -type d); do
-	    j=${i#./}
-	    if cmp -s "${root:=/}$j" "$j"; then
-		rm "$j"
-	    fi
+        unset unrejected
+        cd $rejects/$name 2> /dev/null || return 1
+        for i in $(find . ! -type d); do
+            j=${i#./}
+            if cmp -s "${root:=/}$j" "$j"; then
+                rm "$j"
+            fi
 
-	    if [ ! -e "${root:=/}$j" ] && grep -q "^$j$" $filesnewpackage; then
-		# Workaround files with spaces.
-		k="echo $j | sed -e 's| |\\ |g'"
-		unrejected="$unrejected $k"
-	    fi
-	done
-	if [ -n "$unrejected" ]; then
-	    rm -f $unrejected
-	    $tar -zxpf $path_package -C ${root:=/} $unrejected
-	fi
-	# Remove all empty dirs in $rejects.
-	find $rejects -depth -type d -print0| xargs -0 rmdir > /dev/null 2>&1
-	# Notice all rejects created by this port.
-	find $rejects/$name ! -type d > $TMP1 2> /dev/null
-	if [ -s $TMP1 ]; then
-	    message 'Notice: These files got rejected. Use rejmerge if you want to merge them.'
-	    cat $TMP1
-	fi
+            if [ ! -e "${root:=/}$j" ] && grep -q "^$j$" $filesnewpackage; then
+                # Workaround files with spaces.
+                k="echo $j | sed -e 's| |\\ |g'"
+                unrejected="$unrejected $k"
+            fi
+        done
+        if [ -n "$unrejected" ]; then
+            rm -f $unrejected
+            $tar -zxpf $path_package -C ${root:=/} $unrejected
+        fi
+        # Remove all empty dirs in $rejects.
+        find $rejects -depth -type d -print0| xargs -0 rmdir > /dev/null 2>&1
+        # Notice all rejects created by this port.
+        find $rejects/$name ! -type d > $TMP1 2> /dev/null
+        if [ -s $TMP1 ]; then
+            message 'Notice: These files got rejected. Use rejmerge if you want to merge them.'
+            cat $TMP1
+        fi
     )
 }
 
@@ -283,7 +283,7 @@ dbase()
     root=$1
     dbase=$root/var/package
     if [ ! -d $dbase ]; then
-	error "database directory $dbase not found."
+        error "database directory $dbase not found."
     fi
 }
 
@@ -291,38 +291,38 @@ dbase
 
 while [ $# -gt 0 ]; do
     case $1 in
-	-r|--root)
-	    [ -z $2 ] && error 1 "option \`$1' requires an argument."
-	    dbase $2
-	    shift 2
-	    ;;
-	-f|--force)
-	    FORCE=true
-	    shift
-	    ;;
-	-u|--upgrade)
-	    UPGRADE=true
-	    shift
-	    ;;
-	-v|--version)
-	    version
-	    exit 0
-	    ;;
-	-h|--help)
-	    help
-	    exit 0
-	    ;;
-	-i|--install)
-	    shift
-	    ;;
-	-*)
-	    error 1 "Illegal option: $1"
-	    ;;
-	*)
-	    [ -n "$2" ] && error 1 "packagename must be the last argument."
-	    verifypackage $1
-	    shift
-	    ;;
+        -r|--root)
+            [ -z $2 ] && error 1 "option \`$1' requires an argument."
+            dbase $2
+            shift 2
+            ;;
+        -f|--force)
+            FORCE=true
+            shift
+            ;;
+        -u|--upgrade)
+            UPGRADE=true
+            shift
+            ;;
+        -v|--version)
+            version
+            exit 0
+            ;;
+        -h|--help)
+            help
+            exit 0
+            ;;
+        -i|--install)
+            shift
+            ;;
+        -*)
+            error 1 "Illegal option: $1"
+            ;;
+        *)
+            [ -n "$2" ] && error 1 "packagename must be the last argument."
+            verifypackage $1
+            shift
+            ;;
     esac
 done
 
@@ -345,22 +345,22 @@ find_conflicts
 
 if [ "$UPGRADE" = true ]; then
     if isinstalled $name; then
-	makepattern
-	# Only usefull for packages without metadata.
-	rm -f $dbase/$name-metadata
-	tarcommand $path_package
-	# Only now remove the old files. TODO; ponder on this a
-	# bit more, because of libs.
-	removeoldfiles
+        makepattern
+        # Only usefull for packages without metadata.
+        rm -f $dbase/$name-metadata
+        tarcommand $path_package
+        # Only now remove the old files. TODO; ponder on this a
+        # bit more, because of libs.
+        removeoldfiles
     else
-	error 10 "package \`$name' not previously installed (skip -u to install)"
+        error 10 "package \`$name' was not previously installed (skip -u to install)"
     fi
 else
     if ! isinstalled $name ; then
-	unset pattern
-	tarcommand $path_package
+        unset pattern
+        tarcommand $path_package
     else
-	error 11 "package \`$name' is installed, use $n -u to upgrade."
+        error 11 "package \`$name' is already installed, use $n -u to upgrade."
     fi
 fi
 
@@ -412,10 +412,10 @@ print -n '\aRun this post-install script? [y/N] '
 read answer
 case $answer in
     y*|Y*)
-	post-install
-	exit $?
-	;;
+        post-install
+        exit $?
+        ;;
     *)
-	exit 1
-	;;
+        exit 1
+        ;;
 esac
diff --git a/pkgrm b/pkgrm
--- a/pkgrm
+++ b/pkgrm
@@ -63,12 +63,12 @@ version()
 verifypackage()
 {
     if [ -f "$dbase/$1-metadata" ]; then
-	. $dbase/$1-metadata
-	[ -z "$name"    ] && error 1 "no packagename defined in $dbase/$1"
-	[ -z "$version" ] && error 1 "no versionnumber defined in $dbase/$1"
-	[ -z "$release" ] && error 1 "no releasenumber defined in $dbase/$1"
+        . $dbase/$1-metadata
+        [ -z "$name"    ] && error 1 "no package name defined in $dbase/$1"
+        [ -z "$version" ] && error 1 "no versionnumber defined in $dbase/$1"
+        [ -z "$release" ] && error 1 "no releasenumber defined in $dbase/$1"
     else
-	error 1 "The package \`$1' is not installed."
+        error 1 "The package \`$1' is not installed."
     fi
 }
 
@@ -81,8 +81,8 @@ mktempfiles()
     dirsoldpackage=$DIR/dirsoldpackage
 
     if [ -e $dbase/$name-footprint ]; then
-	awk -F '\t' '/^[^d]/ {print $3}' $dbase/$name-footprint > $filesoldpackage
-	awk -F '\t' '/^d/    {print $3}' $dbase/$name-footprint > $dirsoldpackage
+        awk -F '\t' '/^[^d]/ {print $3}' $dbase/$name-footprint > $filesoldpackage
+        awk -F '\t' '/^d/    {print $3}' $dbase/$name-footprint > $dirsoldpackage
     fi
 
     # remove them in any way the program exits.
@@ -106,7 +106,7 @@ dbase()
     root=$1
     dbase=$root/var/package
     if [ ! -d $dbase ]; then
-	error "database directory $dbase not found."
+        error "database directory $dbase not found."
     fi
 }
 
@@ -114,27 +114,27 @@ dbase
 
 while [ $# -gt 0 ]; do
     case $1 in
-	-r|--root)
-	    [ -z $2 ] && error 1 "option \`$1' requires an argument."
-	    dbase $2
-	    shift 2
-	    ;;
-	-v|--version)
-	    version
-	    exit 0
-	    ;;
-	-h|--help)
-	    help
-	    exit 0
-	    ;;
-	-*)
-	    error 1 "Illegal option: $1"
-	    ;;
-	*)
-	    [ -n "$2" ] && error 1 "packagename must be the last argument."
-	    verifypackage $1
-	    shift
-	    ;;
+        -r|--root)
+            [ -z $2 ] && error 1 "option \`$1' requires an argument."
+            dbase $2
+            shift 2
+            ;;
+        -v|--version)
+            version
+            exit 0
+            ;;
+        -h|--help)
+            help
+            exit 0
+            ;;
+        -*)
+            error 1 "Illegal option: $1"
+            ;;
+        *)
+            [ -n "$2" ] && error 1 "packagename must be the last argument."
+            verifypackage $1
+            shift
+            ;;
     esac
 done
 
@@ -198,12 +198,12 @@ print -n '\aRun this post-install script? [y/N] '
 read answer
 case $answer in
     y*|Y*)
-	post-uninstall
-	exit $?
-	;;
+        post-uninstall
+        exit $?
+        ;;
     *)
-	exit 1
-	;;
+        exit 1
+        ;;
 esac
 
 exit 0
diff --git a/rejmerge b/rejmerge
--- a/rejmerge
+++ b/rejmerge
@@ -41,7 +41,7 @@ interrupted()
 atexit()
 {
     if [ -f "$TMPFILE" ]; then
-	rm -f "$TMPFILE"
+        rm -f "$TMPFILE"
     fi
 }
 
@@ -62,34 +62,34 @@ merge_menu()
     rejmerge_merge "$1" "$2" "$TMPFILE"
 
     while :; do
-	info "Merged $1"
-	$PAGER "$TMPFILE"
+        info "Merged $1"
+        $PAGER "$TMPFILE"
 
-	if [ "$REJMERGE_MERGE_INFO" ]; then
-	    info "$REJMERGE_MERGE_INFO"
-	    unset REJMERGE_MERGE_INFO
-	fi
+        if [ "$REJMERGE_MERGE_INFO" ]; then
+            info "$REJMERGE_MERGE_INFO"
+            unset REJMERGE_MERGE_INFO
+        fi
 
-	while :; do
-	    info_n "[I]nstall [E]dit [V]iew [S]kip? "
-	    read CMD
-	    echo
+        while :; do
+            info_n "[I]nstall [E]dit [V]iew [S]kip? "
+            read CMD
+            echo
 
-	    case "$CMD" in
-		i|I)
-		    # Keep permissions
-		    $SUDO sh -c "cat $TMPFILE > $1"
-		    $SUDO rm -f "$2"
-		    break 2
-		    ;;
-		e|E)
-		    $EDITOR "$TMPFILE"
-		    break 1
-		    ;;
-		v|V) break 1 ;;
-		s|S) break 2 ;;
-	    esac
-	done
+            case "$CMD" in
+                i|I)
+                    # Keep permissions
+                    $SUDO sh -c "cat $TMPFILE > $1"
+                    $SUDO rm -f "$2"
+                    break 2
+                    ;;
+                e|E)
+                    $EDITOR "$TMPFILE"
+                    break 1
+                    ;;
+                v|V) break 1 ;;
+                s|S) break 2 ;;
+            esac
+        done
     done
 
     : > "$TMPFILE"
@@ -100,34 +100,34 @@ diff_menu()
     rejmerge_diff "$1" "$2" "$TMPFILE"
 
     while :; do
-	info "$1"
-	$PAGER "$TMPFILE"
-	while :; do
-	    info_n "[K]eep [U]pgrade [M]erge [D]iff [S]kip? "
-	    read CMD
-	    echo
+        info "$1"
+        $PAGER "$TMPFILE"
+        while :; do
+            info_n "[K]eep [U]pgrade [M]erge [D]iff [S]kip? "
+            read CMD
+            echo
 
-	    case "$CMD" in
-		k|K)
-		    $SUDO rm -f "$2"
-		    break 2
-		    ;;
-		u|U)
-		    $SUDO sh -c "cat $2 > $1"
-		    break 2
-		    ;;
-		m|M)
-		    merge_menu "$1" "$2"
-		    break 2
-		    ;;
-		d|D)
-		    break 1
-		    ;;
-		s|S)
-		    break 2
-		    ;;
-	    esac
-	done
+            case "$CMD" in
+                k|K)
+                    $SUDO rm -f "$2"
+                    break 2
+                    ;;
+                u|U)
+                    $SUDO sh -c "cat $2 > $1"
+                    break 2
+                    ;;
+                m|M)
+                    merge_menu "$1" "$2"
+                    break 2
+                    ;;
+                d|D)
+                    break 1
+                    ;;
+                s|S)
+                    break 2
+                    ;;
+            esac
+        done
     done
 
     : > "$TMPFILE"
@@ -136,30 +136,30 @@ diff_menu()
 file_menu()
 {
     while :; do
-	info "$1"
-	file "$1" "$2"
-	while :; do
-	    info_n "[K]eep [U]pgrade [D]iff [S]kip? "
-	    read CMD
-	    echo
+        info "$1"
+        file "$1" "$2"
+        while :; do
+            info_n "[K]eep [U]pgrade [D]iff [S]kip? "
+            read CMD
+            echo
 
-	    case "$CMD" in
-		k|K)
-		    $SUDO rm -f "$2"
-		    break 2
-		    ;;
-		u|U)
-		    $SUDO sh -c "$2 > $1"
-		    break 2
-		    ;;
-		d|D)
-		    break 1
-		    ;;
-		s|S)
-		    break 2
-		    ;;
-	    esac
-	done
+            case "$CMD" in
+                k|K)
+                    $SUDO rm -f "$2"
+                    break 2
+                    ;;
+                u|U)
+                    $SUDO sh -c "$2 > $1"
+                    break 2
+                    ;;
+                d|D)
+                    break 1
+                    ;;
+                s|S)
+                    break 2
+                    ;;
+            esac
+        done
     done
 }
 
@@ -177,36 +177,36 @@ EOF
 parse_options()
 {
     while [ "$1" ]; do
-	case $1 in
-	    -r|--root)
-		if [ -z "$2" ]; then
-		    echo "$REJMERGE_COMMAND: option $1 requires an argument"
-		    exit 1
-		fi
-		if [ ! -d "$2" ]; then
-		    echo "$REJMERGE_COMMAND: root directory $2 doesn't exist or is no directory."
-		    exit 1
-		fi
-		REJMERGE_ROOT="$2"
-		REJMERGE_CONF="$2$REJMERGE_CONF"
-		REJECTED_DIR="$2$REJECTED_DIR"
-		shift ;;
-	    -v|--version)
-		echo "$REJMERGE_COMMAND (pkgutils) $REJMERGE_VERSION"
-		exit 0 ;;
-	    -h|--help)
-		print_help
-		exit 0 ;;
-	    *)
-		echo "$REJMERGE_COMMAND: invalid option $1"
-		exit 1 ;;
-	esac
-	shift
+        case $1 in
+            -r|--root)
+                if [ -z "$2" ]; then
+                    echo "$REJMERGE_COMMAND: option $1 requires an argument"
+                    exit 1
+                fi
+                if [ ! -d "$2" ]; then
+                    echo "$REJMERGE_COMMAND: root directory $2 doesn't exist or is no directory."
+                    exit 1
+                fi
+                REJMERGE_ROOT="$2"
+                REJMERGE_CONF="$2$REJMERGE_CONF"
+                REJECTED_DIR="$2$REJECTED_DIR"
+                shift ;;
+            -v|--version)
+                echo "$REJMERGE_COMMAND (pkgutils) $REJMERGE_VERSION"
+                exit 0 ;;
+            -h|--help)
+                print_help
+                exit 0 ;;
+            *)
+                echo "$REJMERGE_COMMAND: invalid option $1"
+                exit 1 ;;
+        esac
+        shift
     done
 
     if [ ! -d "$REJECTED_DIR" ]; then
-	echo "$REJMERGE_COMMAND: $REJECTED_DIR not found"
-	exit 1
+        echo "$REJMERGE_COMMAND: $REJECTED_DIR not found"
+        exit 1
     fi
 }
 
@@ -215,48 +215,48 @@ main()
     parse_options "$@"
 
     if [ $(id -u) -eq 0 ]; then
-	echo "$REJMERGE_COMMAND: don't merge rejected files as root"
-	exit 1
+        echo "$REJMERGE_COMMAND: don't merge rejected files as root"
+        exit 1
     fi
 
     # Read configuration
     if [ -f "$REJMERGE_CONF" ]; then
-	. "$REJMERGE_CONF"
+        . "$REJMERGE_CONF"
     fi
 
     REJECTED_FILES_FOUND=no
 
     # Check regular files
     for REJECTED_FILE in $(find $REJECTED_DIR -type f); do
-	clear
-	INSTALLED_FILE="${REJECTED_FILE##$REJECTED_DIR}"
-	INSTALLED_FILE="${REJMERGE_ROOT:=/}${INSTALLED_FILE#/*/}"
-	if [ ! -e "$INSTALLED_FILE" ] || cmp -s "$INSTALLED_FILE" "$REJECTED_FILE"; then
-	    $SUDO rm -f "$REJECTED_FILE"
-	else
-	    REJECTED_FILES_FOUND=yes
-	    diff_menu "$INSTALLED_FILE" "$REJECTED_FILE"
-	fi
+        clear
+        INSTALLED_FILE="${REJECTED_FILE##$REJECTED_DIR}"
+        INSTALLED_FILE="${REJMERGE_ROOT:=/}${INSTALLED_FILE#/*/}"
+        if [ ! -e "$INSTALLED_FILE" ] || cmp -s "$INSTALLED_FILE" "$REJECTED_FILE"; then
+            $SUDO rm -f "$REJECTED_FILE"
+        else
+            REJECTED_FILES_FOUND=yes
+            diff_menu "$INSTALLED_FILE" "$REJECTED_FILE"
+        fi
     done
 
     # Check non-regular files
     for REJECTED_FILE in $(find $REJECTED_DIR ! -type d ! -type f); do
-	clear
-	INSTALLED_FILE="${REJECTED_FILE##$REJECTED_DIR}"
-	INSTALLED_FILE="${REJMERGE_ROOT:=/}${INSTALLED_FILE#/*/}"
- 	if [ ! -e "$INSTALLED_FILE" ]; then
-	    $SUDO rm -f "$REJECTED_FILE"
-	else
-	    REJECTED_FILES_FOUND=yes
-	    file_menu "$INSTALLED_FILE" "$REJECTED_FILE"
-	fi
+        clear
+        INSTALLED_FILE="${REJECTED_FILE##$REJECTED_DIR}"
+        INSTALLED_FILE="${REJMERGE_ROOT:=/}${INSTALLED_FILE#/*/}"
+        if [ ! -e "$INSTALLED_FILE" ]; then
+            $SUDO rm -f "$REJECTED_FILE"
+        else
+            REJECTED_FILES_FOUND=yes
+            file_menu "$INSTALLED_FILE" "$REJECTED_FILE"
+        fi
     done
 
     # Remove empty directories
     $SUDO find $REJECTED_DIR -mindepth 1 -depth -empty -exec rmdir {} \;
 
     if [ "$REJECTED_FILES_FOUND" = no ]; then
-	echo "Nothing to merge"
+        echo "Nothing to merge"
     fi
 
     exit 0
